services:
  web:
    # WAŻNE: Musisz użyć pełnej ścieżki do obrazu (np. GHCR lub Docker Hub)
    image: muniox/portfolio:latest
    container_name: portfolio-container
    restart: unless-stopped
    # Nie mapujemy portów (-p), bo używamy sieci NPM
    # ports:
    #   - "3000:3000" 
    networks:
      - public_net  # To musi być ta sama sieć, w której jest Nginx Proxy Manager

networks:
  public_net:
    external: true