name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]  # Uruchom akcję, gdy ktoś zrobi push na gałąź main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu (Checkout)
        uses: actions/checkout@v3

      - name: Logowanie do Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Zbudowanie i wysłanie obrazu
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Tutaj tworzymy nazwę obrazu: TwójLogin/portfolio:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest